version: '3.4'

x-variables: &environment
  var1: 'pork barrel'

services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:v0.8.0
    ports:
     - "7766:4001" # ipfs swarm - expose if needed/wanted
     - "7767:5001" # ipfs api - expose if needed/wanted
     - "7768:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
      - ./ipfs_add_files:/export
    entrypoint: /sbin/tini
    command: "-- /usr/local/bin/start_ipfs daemon --enable-pubsub-experiment --migrate=true"

  ipfs2:
    container_name: ipfs2
    image: ipfs/go-ipfs:v0.8.0
    ports:
     - "7866:4001" # ipfs swarm - expose if needed/wanted
     - "7867:5001" # ipfs api - expose if needed/wanted
     - "7868:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs2:/data/ipfs
      - ./ipfs2_add_files:/export
    entrypoint: /sbin/tini
    command: "-- /usr/local/bin/start_ipfs daemon --enable-pubsub-experiment --migrate=true"

