version: '3.4'

x-variables: &ciddag-variables
  CIDDAG_HTTP_PORT: "4588"
  CIDDAG_IPFS_API_SERVER: "ipfs0:5001"
  CIDDAG_IPFS_KEYSTORE_PATH: "/data/ipfs/keystore"
  CIDDAG_WL_PROFILEIDS: "${CIDDAG_WL_PROFILEIDS}"
  CIDDAG_IPNS_FEDERATIONMEMBERS: "${CIDDAG_IPNS_FEDERATIONMEMBERS}"
  CIDDAG_TLS_HOSTNAME: "${CIDDAG_TLS_HOSTNAME}"
  CIDDAG_TLS_DATADIR: "/data/tls"

services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:v0.8.0
    ports:
     - "7766:4001" # ipfs swarm - expose if needed/wanted
     # - "7767:5001" # ipfs api - expose if needed/wanted
     # - "7768:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
      - ./ipfs_add_files:/export
    entrypoint: /sbin/tini
    command: "-- /usr/local/bin/start_ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub --migrate=true"

  ipfs2:
    container_name: ipfs2
    image: ipfs/go-ipfs:v0.8.0
    ports:
     - "7866:4001" # ipfs swarm - expose if needed/wanted
     - "7867:5001" # ipfs api - expose if needed/wanted
     - "7868:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs2:/data/ipfs
      - ./ipfs2_add_files:/export
    entrypoint: /sbin/tini
    command: "-- /usr/local/bin/start_ipfs daemon --enable-pubsub-experiment --enable-namesys-pubsub --migrate=true"

  ciddag:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *ciddag-variables
    volumes:
      - ./compose/ipfs0:/data/ipfs
      - ./compose/tlsdata:/data/tls
    ports:
      - "4588:4588"
      - "80:80"
      - "443:443"

  wait_for_deps:
    image: dadarek/wait-for-dependencies
    depends_on:
      - ipfs0
    command: ipfs0:5001


